# - Try to locate SDL2_ttf
# This module defines:
#
#  SDL2_TTF_INCLUDE_DIR
#  SDL2_TTF_LIBRARY
#  SDL2_TTF_FOUND
#

FIND_PATH(SDL2_TTF_INCLUDE_DIR_INSIDE NAMES SDL_ttf.h PATH_SUFFIXES SDL2)
FIND_PATH(SDL2_TTF_INCLUDE_DIR NAMES "SDL2/SDL_ttf.h")
SET(SDL2_TTF_INCLUDE_DIR ${SDL2_TTF_INCLUDE_DIR} ${SDL2_TTF_INCLUDE_DIR_INSIDE})

FIND_LIBRARY(SDL2_TTF_LIBRARY NAMES SDL2_ttf)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_ttf REQUIRED_VARS SDL2_TTF_LIBRARY SDL2_TTF_INCLUDE_DIR)

MARK_AS_ADVANCED(SDL2_TTF_INCLUDE_DIR SDL2_TTF_LIBRARY)
