# - Try to locate SDL2_ttf
# This module defines:
#
#  SDL2_TTF_INCLUDE_DIR
#  SDL2_TTF_LIBRARY
#  SDL2_TTF_FOUND
#

FIND_PATH(SDL2_TTF_INCLUDE_DIR NAMES SDL2/SDL_ttf.h)

FIND_LIBRARY(SDL2_TTF_LIBRARY NAMES SDL2_ttf)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(SDL2_ttf REQUIRED_VARS SDL2_TTF_INCLUDE_DIR SDL2_TTF_LIBRARY)

MARK_AS_ADVANCED(SDL2_TTF_INCLUDE_DIR SDL2_TTF_LIBRARY)
