# SDL2::SDL2_ttf

find_path(SDL2_TTF_INCLUDE_DIR NAMES SDL_ttf.h PATH_SUFFIXES SDL2)
find_library(SDL2_TTF_LIBRARY NAMES SDL2_ttf)

if(SDL2_TTF_INCLUDE_DIR AND SDL2_TTF_LIBRARY)
	add_library(SDL2::SDL2_ttf UNKNOWN IMPORTED)
	set_property(TARGET SDL2::SDL2_ttf PROPERTY IMPORTED_LOCATION ${SDL2_TTF_LIBRARY})
	set_target_properties(SDL2::SDL2_ttf PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${SDL2_TTF_INCLUDE_DIR})

	message(STATUS "Found SDL2_ttf: ${SDL2_TTF_LIBRARY}")
else()
	message(FATAL_ERROR "Could not find SDL2_ttf")
endif()
