# SDL2::SDL2_mixer

find_path(SDL2_MIXER_INCLUDE_DIR NAMES SDL_mixer.h PATH_SUFFIXES SDL2)
find_library(SDL2_MIXER_LIBRARY NAMES SDL2_mixer)

if(SDL2_MIXER_INCLUDE_DIR AND SDL2_MIXER_LIBRARY)
	add_library(SDL2::SDL2_mixer UNKNOWN IMPORTED)
	set_property(TARGET SDL2::SDL2_mixer PROPERTY IMPORTED_LOCATION ${SDL2_MIXER_LIBRARY})
	set_target_properties(SDL2::SDL2_mixer PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${SDL2_MIXER_INCLUDE_DIR})

	message(STATUS "Found SDL2_mixer: ${SDL2_MIXER_LIBRARY}")
else()
	message(FATAL_ERROR "Could not find SDL2_mixer")
endif()
